name: chempro310
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - rdkit
  - openbabel
  - gemmi
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - pytorch-cuda=11.8
  - tqdm
  - requests
  - pyyaml
  - click
  - joblib
  - pip:
      - transformers
      - datasets
      - accelerate
      - peft
      - trl
      - tokenizers==0.13.3
      - langchain
      - langchain-core
      - langsmith
      - openai
      - anthropic
      - streamlit
      - altair
      - beautifulsoup4
      - lxml
      - html2text
      - wandb
      - tiktoken
      - regex
      - chemcrow
      - ChatterBot
      - google_speech
      - RXN4Chemistry
      - synspace
      - molscrub
      - molbloom
